name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
        fma: [ON, OFF]
    steps:
    - uses: actions/checkout@v5          # ← 这里从 v4 改为 v5
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ clang
    - name: Build and run test and run benchmark
      run: |
        FMA_FLAG=""
        if [ "${{ matrix.fma }}" = "ON" ]; then
          FMA_FLAG="-mfma"
        fi
        ${{ matrix.compiler }} -O3 -march=native $FMA_FLAG -std=c++98 PolyAVX-AVX_bench_basic.cpp cpu_dispatch.cpp -o PolyAVX-AVX_bench_basic.exe
        ./PolyAVX-AVX_bench_basic.exe
